name: adwaita_icons
description: Package that contains all icons built for the Adwaita Theme.
version: 0.2.0
homepage: https://github.com/jesusrp98/adwaita_icons/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.22.0

flutter:
  assets:
    - assets/icons/
